create_clock -name CLK50m -period 20 -waveform {10 20} [get_ports {CLK50m}]
derive_pll_clocks
rename_clock -name {hdmi_clk} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {pll_hdmi_inst/pll_inst.clkc[0]}]
rename_clock -name {hdmi_clk_5} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {pll_hdmi_inst/pll_inst.clkc[1]}]
rename_clock -name {clk_100MHz} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_clk_pll/pll_inst.clkc[0]}]
rename_clock -name {clk_25p2MHz} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_clk_pll/pll_inst.clkc[1]}]
rename_clock -name {clk_125MHz} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_clk_pll/pll_inst.clkc[2]}]
rename_clock -name {clk_100m} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_pll/pll_inst.clkc[0]}]
rename_clock -name {clk_100m_shift} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_pll/pll_inst.clkc[1]}]
rename_clock -name {clk_50m} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_pll/pll_inst.clkc[2]}]
set_clock_groups -exclusive -group [get_clocks {clk_100m clk_100m_shift clk_50m}] -group [get_clocks {hdmi_clk hdmi_clk_5}] -group [get_clocks {clk_100MHz clk_125MHz clk_25p2MHz}] -group [get_clocks {CLK50m}]
# derive_pll_clocks -instance [get_cells {u_clk_pll/pll_inst}]
# rename_clock -name {clk_100MHz} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_clk_pll/pll_inst.clkc[0]}]
# rename_clock -name {clk_25p2MHz} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_clk_pll/pll_inst.clkc[1]}]
# rename_clock -name {clk_125MHz} -source [get_ports {CLK50m}] -master_clock {CLK50m} [get_pins {u_clk_pll/pll_inst.clkc[2]}]
# set_clock_groups -exclusive -group [get_clocks {clk_100MHz clk_125MHz clk_25p2MHz}] -group [get_clocks {CLK50m}]