set_property PACKAGE_PIN K18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN B16 [get_ports RSTn]
set_property IOSTANDARD LVCMOS33 [get_ports RSTn]
set_property PACKAGE_PIN AB22 [get_ports RXD]
set_property PACKAGE_PIN AB21 [get_ports TXD]
set_property PACKAGE_PIN J15 [get_ports SWCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RXD]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SWDIO]
set_property IOSTANDARD LVCMOS33 [get_ports TXD]
set_property PACKAGE_PIN AB10 [get_ports {col[0]}]
set_property PACKAGE_PIN W11 [get_ports {col[1]}]
set_property PACKAGE_PIN AA11 [get_ports {col[2]}]
set_property PACKAGE_PIN T14 [get_ports {col[3]}]
set_property PACKAGE_PIN AA10 [get_ports {row[3]}]
set_property PACKAGE_PIN V10 [get_ports {row[2]}]
set_property PACKAGE_PIN W10 [get_ports {row[1]}]
set_property PACKAGE_PIN AA9 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUTLED[0]}]
set_property PACKAGE_PIN AA21 [get_ports {OUTLED[0]}]
set_property PACKAGE_PIN P19 [get_ports {OUTLED[1]}]
set_property PACKAGE_PIN P20 [get_ports {OUTLED[2]}]
set_property PACKAGE_PIN R19 [get_ports {OUTLED[3]}]
set_property PACKAGE_PIN T20 [get_ports {OUTLED[4]}]
set_property PACKAGE_PIN T21 [get_ports {OUTLED[5]}]
set_property PACKAGE_PIN U21 [get_ports {OUTLED[6]}]
set_property PACKAGE_PIN U22 [get_ports {OUTLED[7]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SWCLK_IBUF]


#LCD
set_property PACKAGE_PIN K19 [get_ports LCD_BL_CTR]
set_property PACKAGE_PIN J21 [get_ports LCD_CS]
set_property PACKAGE_PIN J20 [get_ports LCD_RS]
set_property PACKAGE_PIN M15 [get_ports LCD_RD]
set_property PACKAGE_PIN L13 [get_ports LCD_RST]
set_property PACKAGE_PIN M16 [get_ports LCD_WR]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_BL_CTR]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RD]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RST]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_WR]
set_property PACKAGE_PIN M17 [get_ports {LCD_DATA[15]}]
set_property PACKAGE_PIN J19 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN H19 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN H17 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN H18 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN K17 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN J17 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN M18 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN L18 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN L16 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN K16 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN K13 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN K14 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN L14 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN L15 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN M13 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]

#CAMERA
set_property PACKAGE_PIN N14 [get_ports CAMERA_VSYNC]
set_property PACKAGE_PIN R16 [get_ports CAMERA_HREF]
set_property PACKAGE_PIN N20 [get_ports CAMERA_PCLK]
set_property PACKAGE_PIN N22 [get_ports CAMERA_PWDN]
set_property PACKAGE_PIN T18 [get_ports CAMERA_RST]
set_property PACKAGE_PIN N13 [get_ports CAMERA_SCL]
set_property PACKAGE_PIN P15 [get_ports CAMERA_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_HREF]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_PWDN]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_RST]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_VSYNC]
set_property PACKAGE_PIN M20 [get_ports {CAMERA_DATA[7]}]
set_property PACKAGE_PIN L19 [get_ports {CAMERA_DATA[6]}]
set_property PACKAGE_PIN L20 [get_ports {CAMERA_DATA[5]}]
set_property PACKAGE_PIN N18 [get_ports {CAMERA_DATA[4]}]
set_property PACKAGE_PIN N19 [get_ports {CAMERA_DATA[3]}]
set_property PACKAGE_PIN N17 [get_ports {CAMERA_DATA[2]}]
set_property PACKAGE_PIN P17 [get_ports {CAMERA_DATA[1]}]
set_property PACKAGE_PIN R18 [get_ports {CAMERA_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CAMERA_PCLK_IBUF]

#SPI
set_property PACKAGE_PIN M21 [get_ports SPI_CS]
set_property PACKAGE_PIN K21 [get_ports SPI_CLK]
set_property PACKAGE_PIN H13 [get_ports SPI_MISO]
set_property PACKAGE_PIN J14 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]

#VGA
set_property PACKAGE_PIN T15 [get_ports hsync]
set_property PACKAGE_PIN V13 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN U16 [get_ports {rgb[11]}]
set_property PACKAGE_PIN W15 [get_ports {rgb[10]}]
set_property PACKAGE_PIN W16 [get_ports {rgb[9]}]
set_property PACKAGE_PIN R17 [get_ports {rgb[8]}]
set_property PACKAGE_PIN V14 [get_ports {rgb[7]}]
set_property PACKAGE_PIN U15 [get_ports {rgb[6]}]
set_property PACKAGE_PIN V15 [get_ports {rgb[5]}]
set_property PACKAGE_PIN T16 [get_ports {rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]


create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]

set_property PACKAGE_PIN K18 [get_ports clk_50MHz]
set_property PACKAGE_PIN B16 [get_ports sys_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50MHz]

set_property PACKAGE_PIN B16 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]

set_property PACKAGE_PIN J22 [get_ports PS2_CLK]
set_property PACKAGE_PIN H20 [get_ports PS2_CS]
set_property PACKAGE_PIN H22 [get_ports PS2_DI]
set_property PACKAGE_PIN G20 [get_ports PS2_DO]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CS]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DI]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DO]

set_property PACKAGE_PIN Y12 [get_ports {rgb[3]}]
set_property PACKAGE_PIN W12 [get_ports {rgb[2]}]
set_property PACKAGE_PIN P16 [get_ports {rgb[1]}]
set_property PACKAGE_PIN AB12 [get_ports {rgb[0]}]


set_property PACKAGE_PIN H15 [get_ports SWDIO]

set_property PACKAGE_PIN AA20 [get_ports SLEEPING]
set_property IOSTANDARD LVCMOS33 [get_ports SLEEPING]

# 异步时钟约束 2023.04.17
set_clock_groups -name clk_100MHz_25p2MHz_async -asynchronous -group [get_clocks [list [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT1]] [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0]]]]

